#!/bin/sh
export PERL5LIB=$PERL5LIB:/kb/deployment/lib
export KB_DEPLOYMENT_CONFIG=/homes/oakland/jkbaumohl/expression_instance/test.cfg
export KB_SERVICE_NAME=expressionServices
export STARMAN_DEBUG=1
/kb/runtime/bin/starman --listen :9999 --workers 1 \
    /kb/deployment/lib/
