#!/bin/sh
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export KB_SERVICE_NAME=KBaseExpression
export STARMAN_DEBUG=1
$KB_RUNTIME/bin/starman --listen :7075 --workers 1 \
    $KB_TOP/lib/KBaseExpression.psgi
