#!/bin/sh

echo starting KBaseExpression service.
export KB_DEPLOYMENT_CONFIG=$KB_TOP/deployment.cfg
export KB_SERVICE_NAME=KBaseExpression
export KB_SERVICE_DIR=$KB_TOP/services/$KB_SERVICE_NAME
#uncomment to debug: export STARMAN_DEBUG=1
$KB_RUNTIME/bin/starman --listen :7075 --pid $KB_SERVICE_DIR/service.pid --daemonize \
  --access-log $KB_SERVICE_DIR/log/access.log \
  --error-log $KB_SERVICE_DIR/log/error.log \
  $KB_TOP/lib/KBaseExpression.psgi
echo KBaseExpression service is listening on port 7075.

